# -*- coding: utf-8 -*-
"""assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18PLaopxEuS92MjnFOG_--rZ22XG1vTYv
"""





from scipy.stats import poisson
from matplotlib import pyplot as plt

_lambda=1
simlen=100000
count_2=0
count_3=0
count_4=0
r=poisson.rvs(_lambda,size=simlen)
for i in range(0,simlen):
  if(r[i]==2):
    count_2=count_2+1
  if(r[i]==3):
    count_3=count_3+1
  if(r[i]==4):
    count_4=count_4+1

prob_2=count_2/simlen
prob_3=count_3/simlen
prob_4=count_4/simlen

required_prob_simulated=prob_2+prob_3+prob_4

required_prob_theoritical=poisson.pmf(2,1)+poisson.pmf(3,1)+poisson.pmf(4,1)

cases=['i']

x = np.arange(len(cases))
plt.bar(x + 0.00,required_prob_theoritical , color = 'green', width = 0.25, label = 'Theoretical')
plt.bar(x + 1,required_prob_simulated , color = 'violet', width = 0.25, label = 'Sim')
plt.xlabel('Cases')
plt.ylabel('Probabilities')

plt.legend()
plt.show()