# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZsO6Ox7VhBeWYvnOPRyhhIVl5tPmSXLz
"""

from scipy.stats import poisson
from numpy import random
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

simlen=10000

data = np.random.poisson(lam=10,size=simlen)
sns.distplot(data, hist=False, label='poisson')

plt.show()

data_=poisson.rvs(mu=30, size=simlen)
ax=sns.distplot(data_,kde=False,color='skyblue',hist_kws={"linewidth":25,'alpha':1})

ax.set_title('Poisson Distribution')
ax.set(xlabel='Poisson')
ax.set(ylabel='Frequency')