# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lQVIZ6S7F4M7E_PIF6RY33MlBbyp3TeH
"""

import random
import math
import statistics
import matplotlib.pyplot as plt

_lambda=5
num_events=100
event_num=[]
inter_event_times=[]
event_times=[]
event_time=0

for i in range(num_events):
  event_num.append(i)

  #get a random probability value from the uniform distribution
  n=random.random()

  #generating inter event time from exponential distribution of CDF
  inter_event_time=-math.log(1.0-n)/_lambda
  inter_event_times.append(inter_event_time)

  #adding inter event time to the sum to get next event time
  event_time=event_time+inter_event_time
  event_times.append(event_time)


#plotting each event times
fig=plt.figure()
fig.suptitle('Time of occurence of events in a simulated poisson process')
plot,=plt.plot(event_num,event_times,'bo-',label='Time of event')
plt.legend(handles=[plot])

plt.xlabel('Index of event')
plt.ylabel('Time')
plt.show()