# -*- coding: utf-8 -*-
"""assignment2(gautham).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S8a6iAEOxUk3gr61lKrdwrkjaTwyMlX7
"""

import numpy as np
import scipy 
import math
import matplotlib.pyplot as plt
from scipy.stats import bernoulli

maxrange= 25
maxlim=25.0
x = np.linspace(0,maxlim,maxrange)
x1 = np.linspace(0,maxlim,250)
simlen = int(1e5)
pdf = [] 
data = []
lam = 5
num = 10000
prob = lam/num

for i in range(0, simlen-1):
    data_bern = bernoulli.rvs(size = num, p = prob)
    data.append(np.size(np.nonzero(data_bern == 1)))

for i in range(0, num):
    pdf.append(data.count(i)/simlen)

def poisson_pdf(x1):
    return math.exp(-lam)*pow(lam,x1)/math.gamma(x1+1)

vec_poisson_pdf = scipy.vectorize(poisson_pdf)

plt.plot(x[0:maxrange],pdf[0:maxrange], 'o')
plt.plot(x1,vec_poisson_pdf(x1))
plt.grid()
plt.xlabel('$x_i$')
plt.ylabel('${Pr}_X(x_i)$')

plt.show()